# Ime delovnega toka za deployment
name: Deployment na DockerHub

# Sproži se samo ko se test workflow uspešno zaključi
on:
  workflow_run:
    workflows: ["CI Tests"]  # Ime test workflowa
    types:
      - completed
    branches: [main]

jobs:
  # Preveri če so testi bili uspešni
  check-tests:
    name: Preverjanje uspešnosti testov
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Preveri status testov
        run: echo "Testi so bili uspešni, nadaljujem z deploymentom"

  # Zgradi in objavi Docker image
  deploy:
    name: Deployment Docker zabojnikov
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    
    strategy:
      matrix:
        # Uporabimo matriko za različne komponente
        component: [client, server]
    
    steps:
      # Pridobimo kodo iz repozitorija
      - name: Prenos kode
        uses: actions/checkout@v4

      # Dodamo korak za preverjanje Docker pravic
      - name: Preveri Docker pravice
        run: |
          id
          groups
          ls -l /var/run/docker.sock
          docker info || exit 1

      # Posodobljene verzije Docker akcij
      - name: Prijava v DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Nastavimo Docker Buildx
      - name: Nastavitev Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          use: true
          driver-opts: |
            image=moby/buildkit:latest

      # Zgradimo in objavimo Docker image
      - name: Gradnja in objava ${{ matrix.component }} zabojnika
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.component }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.component }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.component }}:${{ github.sha }}

      # Beležimo uspešnost deploymenta
      - name: Status deploymenta
        run: |
          echo "Uspešno objavljen ${{ matrix.component }} zabojnik na DockerHub"
          echo "Tag: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.component }}:${{ github.sha }}" 